import {
  Ride,
  Driver,
  Chaperone,
  Passenger,
  Vehicle,
} from "@/types";

// ---------- Vehicles ----------
export const mockVehicles: Vehicle[] = [
  {
    id: "v1",
    licensePlate: "TR-1042",
    make: "Toyota",
    model: "Sienna",
    year: 2022,
    currentMileage: 48320,
    lastServiceDate: "2026-02-15",
    inspectionStatus: "Valid",
  },
  {
    id: "v2",
    licensePlate: "TR-2087",
    make: "Ford",
    model: "Transit",
    year: 2021,
    currentMileage: 72190,
    lastServiceDate: "2026-01-20",
    inspectionStatus: "Valid",
  },
  {
    id: "v3",
    licensePlate: "TR-3301",
    make: "Honda",
    model: "Odyssey",
    year: 2023,
    currentMileage: 22850,
    lastServiceDate: "2026-03-01",
    inspectionStatus: "Valid",
  },
  {
    id: "v4",
    licensePlate: "TR-4418",
    make: "Chrysler",
    model: "Pacifica",
    year: 2022,
    currentMileage: 61400,
    lastServiceDate: "2025-12-10",
    inspectionStatus: "Valid",
  },
  {
    id: "v5",
    licensePlate: "TR-5529",
    make: "Ford",
    model: "Explorer",
    year: 2020,
    currentMileage: 88900,
    lastServiceDate: "2025-11-22",
    inspectionStatus: "Expired",
  },
  {
    id: "v6",
    licensePlate: "TR-6603",
    make: "Toyota",
    model: "Highlander",
    year: 2023,
    currentMileage: 19200,
    lastServiceDate: "2026-03-15",
    inspectionStatus: "Valid",
  },
];

// ---------- Drivers ----------
export const mockDrivers: Driver[] = [
  {
    id: "d1",
    firstName: "Marcus",
    lastName: "Williams",
    phone: "(555) 234-1100",
    email: "m.williams@trustedriders.com",
    licenseNumber: "DL-8823401",
    licenseExpiration: "2027-08-14",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-06-01",
    medicalTransportCertified: true,
    firstAidCertified: true,
    firstAidExpirationDate: "2026-11-30",
    defensiveDrivingCertified: true,
    defensiveDrivingDate: "2025-09-15",
    vehicle: mockVehicles[0],
    status: "OnRide",
    hireDate: "2022-03-14",
    yearsOfService: 4,
    totalRidesCompleted: 1842,
    onTimePercentage: 94,
    averageRating: 4.8,
    isActive: true,
    currentRideId: "ride-1",
  },
  {
    id: "d2",
    firstName: "Sarah",
    lastName: "Chen",
    phone: "(555) 234-1101",
    email: "s.chen@trustedriders.com",
    licenseNumber: "DL-4471209",
    licenseExpiration: "2028-04-22",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-07-15",
    medicalTransportCertified: true,
    firstAidCertified: true,
    firstAidExpirationDate: "2027-03-10",
    defensiveDrivingCertified: true,
    defensiveDrivingDate: "2025-10-02",
    vehicle: mockVehicles[1],
    status: "OnRide",
    hireDate: "2021-08-30",
    yearsOfService: 5,
    totalRidesCompleted: 2310,
    onTimePercentage: 97,
    averageRating: 4.9,
    isActive: true,
    currentRideId: "ride-2",
  },
  {
    id: "d3",
    firstName: "Derek",
    lastName: "Johnson",
    phone: "(555) 234-1102",
    email: "d.johnson@trustedriders.com",
    licenseNumber: "DL-9903817",
    licenseExpiration: "2026-12-05",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-05-20",
    medicalTransportCertified: true,
    firstAidCertified: true,
    firstAidExpirationDate: "2026-08-15",
    defensiveDrivingCertified: false,
    defensiveDrivingDate: null,
    vehicle: mockVehicles[2],
    status: "Available",
    hireDate: "2023-01-10",
    yearsOfService: 3,
    totalRidesCompleted: 892,
    onTimePercentage: 88,
    averageRating: 4.6,
    isActive: true,
    currentRideId: null,
  },
  {
    id: "d4",
    firstName: "Priya",
    lastName: "Patel",
    phone: "(555) 234-1103",
    email: "p.patel@trustedriders.com",
    licenseNumber: "DL-7721534",
    licenseExpiration: "2029-02-18",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2026-01-10",
    medicalTransportCertified: true,
    firstAidCertified: true,
    firstAidExpirationDate: "2027-09-20",
    defensiveDrivingCertified: true,
    defensiveDrivingDate: "2025-12-08",
    vehicle: mockVehicles[3],
    status: "Available",
    hireDate: "2024-06-01",
    yearsOfService: 2,
    totalRidesCompleted: 487,
    onTimePercentage: 91,
    averageRating: 4.7,
    isActive: true,
    currentRideId: null,
  },
  {
    id: "d5",
    firstName: "James",
    lastName: "Rivera",
    phone: "(555) 234-1104",
    email: "j.rivera@trustedriders.com",
    licenseNumber: "DL-3345678",
    licenseExpiration: "2027-06-30",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-04-14",
    medicalTransportCertified: true,
    firstAidCertified: false,
    firstAidExpirationDate: null,
    defensiveDrivingCertified: true,
    defensiveDrivingDate: "2025-08-22",
    vehicle: mockVehicles[4],
    status: "OffDuty",
    hireDate: "2020-11-05",
    yearsOfService: 6,
    totalRidesCompleted: 3120,
    onTimePercentage: 85,
    averageRating: 4.5,
    isActive: true,
    currentRideId: null,
  },
  {
    id: "d6",
    firstName: "Angela",
    lastName: "Thompson",
    phone: "(555) 234-1105",
    email: "a.thompson@trustedriders.com",
    licenseNumber: "DL-6689023",
    licenseExpiration: "2028-09-11",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-09-01",
    medicalTransportCertified: true,
    firstAidCertified: true,
    firstAidExpirationDate: "2027-05-30",
    defensiveDrivingCertified: true,
    defensiveDrivingDate: "2026-01-15",
    vehicle: mockVehicles[5],
    status: "OnRide",
    hireDate: "2022-07-19",
    yearsOfService: 4,
    totalRidesCompleted: 1654,
    onTimePercentage: 96,
    averageRating: 4.9,
    isActive: true,
    currentRideId: "ride-3",
  },
];

// ---------- Chaperones ----------
export const mockChaperones: Chaperone[] = [
  {
    id: "c1",
    firstName: "Linda",
    lastName: "Garcia",
    phone: "(555) 345-2200",
    email: "l.garcia@trustedriders.com",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-06-10",
    medicalTransportCertified: true,
    medicalTransportExpiration: "2027-06-10",
    firstAidCertified: true,
    firstAidExpiration: "2026-12-01",
    cprCertified: true,
    cprExpiration: "2026-12-01",
    specializations: ["dementia_care", "mobility_assistance"],
    status: "OnAssignment",
    hireDate: "2021-04-22",
    yearsOfService: 5,
    totalAssignmentsCompleted: 2180,
    isActive: true,
    currentRideId: "ride-1",
  },
  {
    id: "c2",
    firstName: "Robert",
    lastName: "Kim",
    phone: "(555) 345-2201",
    email: "r.kim@trustedriders.com",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-08-01",
    medicalTransportCertified: true,
    medicalTransportExpiration: "2027-08-01",
    firstAidCertified: true,
    firstAidExpiration: "2027-02-15",
    cprCertified: true,
    cprExpiration: "2027-02-15",
    specializations: ["pediatric", "mobility_assistance"],
    status: "Available",
    hireDate: "2023-02-14",
    yearsOfService: 3,
    totalAssignmentsCompleted: 945,
    isActive: true,
    currentRideId: null,
  },
  {
    id: "c3",
    firstName: "Maria",
    lastName: "Santos",
    phone: "(555) 345-2202",
    email: "m.santos@trustedriders.com",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-07-20",
    medicalTransportCertified: true,
    medicalTransportExpiration: "2027-07-20",
    firstAidCertified: true,
    firstAidExpiration: "2026-10-30",
    cprCertified: true,
    cprExpiration: "2026-10-30",
    specializations: ["dementia_care", "behavioral_support"],
    status: "OnAssignment",
    hireDate: "2020-09-01",
    yearsOfService: 6,
    totalAssignmentsCompleted: 3340,
    isActive: true,
    currentRideId: "ride-2",
  },
  {
    id: "c4",
    firstName: "Kevin",
    lastName: "Brown",
    phone: "(555) 345-2203",
    email: "k.brown@trustedriders.com",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2026-01-05",
    medicalTransportCertified: true,
    medicalTransportExpiration: "2028-01-05",
    firstAidCertified: true,
    firstAidExpiration: "2027-07-10",
    cprCertified: true,
    cprExpiration: "2027-07-10",
    specializations: ["mobility_assistance"],
    status: "Available",
    hireDate: "2024-11-18",
    yearsOfService: 1,
    totalAssignmentsCompleted: 213,
    isActive: true,
    currentRideId: null,
  },
  {
    id: "c5",
    firstName: "Susan",
    lastName: "Lee",
    phone: "(555) 345-2204",
    email: "s.lee@trustedriders.com",
    backgroundCheckStatus: "Verified",
    backgroundCheckDate: "2025-05-30",
    medicalTransportCertified: true,
    medicalTransportExpiration: "2027-05-30",
    firstAidCertified: true,
    firstAidExpiration: "2026-11-15",
    cprCertified: true,
    cprExpiration: "2026-11-15",
    specializations: ["dementia_care", "pediatric", "mobility_assistance"],
    status: "OffDuty",
    hireDate: "2019-06-03",
    yearsOfService: 7,
    totalAssignmentsCompleted: 4120,
    isActive: true,
    currentRideId: null,
  },
];

// ---------- Passengers ----------
export const mockPassengers: Passenger[] = [
  {
    id: "p1",
    firstName: "Eleanor",
    lastName: "Whitfield",
    phone: "(555) 401-0011",
    dateOfBirth: "1948-03-22",
    address: "412 Maple Lane, Springfield, IL 62701",
    emergencyContactName: "Dorothy Whitfield",
    emergencyContactPhone: "(555) 401-0012",
    accessibilityNeeds: ["wheelchair", "requires_assistance"],
    medicalNotes: "Dialysis patient — handle with care. Arm fistula on left arm, avoid blood pressure cuff on left arm.",
  },
  {
    id: "p2",
    firstName: "Harold",
    lastName: "Nguyen",
    phone: "(555) 401-0021",
    dateOfBirth: "1955-07-04",
    address: "88 Oak Street, Springfield, IL 62702",
    emergencyContactName: "Janet Nguyen",
    emergencyContactPhone: "(555) 401-0022",
    accessibilityNeeds: ["walker"],
    medicalNotes: "Post knee replacement surgery. Physical therapy 3x weekly.",
  },
  {
    id: "p3",
    firstName: "Dorothy",
    lastName: "Ramirez",
    phone: "(555) 401-0031",
    dateOfBirth: "1942-11-15",
    address: "203 Pine Avenue, Springfield, IL 62703",
    emergencyContactName: "Carlos Ramirez",
    emergencyContactPhone: "(555) 401-0032",
    accessibilityNeeds: ["wheelchair", "oxygen_equipment"],
    medicalNotes: "Requires portable oxygen concentrator. Mild dementia — may be confused about destination.",
  },
  {
    id: "p4",
    firstName: "George",
    lastName: "Okafor",
    phone: "(555) 401-0041",
    dateOfBirth: "1961-05-30",
    address: "556 Elm Court, Springfield, IL 62704",
    emergencyContactName: "Amara Okafor",
    emergencyContactPhone: "(555) 401-0042",
    accessibilityNeeds: [],
    medicalNotes: "Cardiac patient. Monthly cardiology follow-up.",
  },
  {
    id: "p5",
    firstName: "Ruth",
    lastName: "Hernandez",
    phone: "(555) 401-0051",
    dateOfBirth: "1938-09-12",
    address: "917 Birch Road, Springfield, IL 62705",
    emergencyContactName: "Miguel Hernandez",
    emergencyContactPhone: "(555) 401-0052",
    accessibilityNeeds: ["wheelchair"],
    medicalNotes: "Dialysis patient (Tuesdays, Thursdays, Saturdays). Cannot wait more than 15 min at pickup.",
  },
  {
    id: "p6",
    firstName: "Frank",
    lastName: "Morrison",
    phone: "(555) 401-0061",
    dateOfBirth: "1950-02-28",
    address: "34 Willow Way, Springfield, IL 62706",
    emergencyContactName: "Cindy Morrison",
    emergencyContactPhone: "(555) 401-0062",
    accessibilityNeeds: ["cane"],
    medicalNotes: "Diabetic. May need extra time at appointments. Insulin dependent.",
  },
  {
    id: "p7",
    firstName: "Alice",
    lastName: "Yamamoto",
    phone: "(555) 401-0071",
    dateOfBirth: "1944-12-03",
    address: "72 Cedar Lane, Springfield, IL 62707",
    emergencyContactName: "Tom Yamamoto",
    emergencyContactPhone: "(555) 401-0072",
    accessibilityNeeds: ["hearing_impaired"],
    medicalNotes: "Hearing impaired — speak clearly and directly. Oncology appointments bi-weekly.",
  },
  {
    id: "p8",
    firstName: "Bernard",
    lastName: "Kowalski",
    phone: "(555) 401-0081",
    dateOfBirth: "1958-08-19",
    address: "291 Spruce Street, Springfield, IL 62708",
    emergencyContactName: "Helen Kowalski",
    emergencyContactPhone: "(555) 401-0082",
    accessibilityNeeds: ["walker", "requires_assistance"],
    medicalNotes: "Parkinson's disease. Tremors may affect boarding. Allow extra time.",
  },
  {
    id: "p9",
    firstName: "Margaret",
    lastName: "Sullivan",
    phone: "(555) 401-0091",
    dateOfBirth: "1946-04-07",
    address: "128 Aspen Drive, Springfield, IL 62709",
    emergencyContactName: "Patrick Sullivan",
    emergencyContactPhone: "(555) 401-0092",
    accessibilityNeeds: ["wheelchair"],
    medicalNotes: "Routine lab work and specialist visits. Generally cooperative.",
  },
  {
    id: "p10",
    firstName: "Thomas",
    lastName: "Blake",
    phone: "(555) 401-0101",
    dateOfBirth: "1963-06-25",
    address: "445 Hickory Blvd, Springfield, IL 62710",
    emergencyContactName: "Sandra Blake",
    emergencyContactPhone: "(555) 401-0102",
    accessibilityNeeds: [],
    medicalNotes: "Mental health outpatient appointments. Occasional anxiety — chaperone should remain calm and reassuring.",
  },
];

// ---------- Today base time for realistic data ----------
const TODAY = "2026-04-09";

// ---------- Rides ----------
export const mockRides: Ride[] = [
  // Active: DriverEnRoute
  {
    id: "ride-1",
    confirmationNumber: "TR-20260409-001",
    passenger: mockPassengers[0],
    driver: mockDrivers[0],
    chaperone: mockChaperones[0],
    pickupTime: `${TODAY}T08:00:00`,
    estimatedArrivalTime: `${TODAY}T09:15:00`,
    actualPickupTime: null,
    actualArrivalTime: null,
    status: "DriverEnRoute",
    pickupAddress: "412 Maple Lane, Springfield, IL 62701",
    dropoffAddress: "Springfield Dialysis Center, 800 N Grand Ave, Springfield, IL 62702",
    estimatedDistance: 6.2,
    estimatedDuration: 18,
    medicalNotes: "Dialysis patient — arm fistula on left arm. Do not apply blood pressure cuff to left arm.",
    specialInstructions: "Passenger uses motorized wheelchair. Ensure vehicle ramp is deployed before passenger boards.",
    accessibilityNeeds: ["wheelchair", "requires_assistance"],
    createdAt: `${TODAY}T07:00:00`,
    updatedAt: `${TODAY}T07:42:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T07:00:00`, status: "Scheduled", changedBy: "Dispatcher", note: "Ride created" },
      { timestamp: `${TODAY}T07:42:00`, status: "DriverEnRoute", changedBy: "Marcus Williams", note: "Driver en route to pickup" },
    ],
    notes: ["Patient confirmed pickup via phone at 7:50 AM"],
  },

  // Active: PassengerPickedUp
  {
    id: "ride-2",
    confirmationNumber: "TR-20260409-002",
    passenger: mockPassengers[1],
    driver: mockDrivers[1],
    chaperone: mockChaperones[2],
    pickupTime: `${TODAY}T08:30:00`,
    estimatedArrivalTime: `${TODAY}T09:00:00`,
    actualPickupTime: `${TODAY}T08:28:00`,
    actualArrivalTime: null,
    status: "PassengerPickedUp",
    pickupAddress: "88 Oak Street, Springfield, IL 62702",
    dropoffAddress: "Springfield Physical Therapy, 1201 S Sixth St, Springfield, IL 62703",
    estimatedDistance: 4.8,
    estimatedDuration: 14,
    medicalNotes: "Post knee replacement. Patient is mobile but slow. Allow extra boarding time.",
    specialInstructions: "Passenger uses walker — ensure secure seating before departure.",
    accessibilityNeeds: ["walker"],
    createdAt: `${TODAY}T07:15:00`,
    updatedAt: `${TODAY}T08:28:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T07:15:00`, status: "Scheduled", changedBy: "Dispatcher", note: "Ride created" },
      { timestamp: `${TODAY}T08:05:00`, status: "DriverEnRoute", changedBy: "Sarah Chen" },
      { timestamp: `${TODAY}T08:28:00`, status: "PassengerPickedUp", changedBy: "Sarah Chen", note: "Picked up on time" },
    ],
    notes: [],
  },

  // Active: InTransit
  {
    id: "ride-3",
    confirmationNumber: "TR-20260409-003",
    passenger: mockPassengers[2],
    driver: mockDrivers[5],
    chaperone: null,
    pickupTime: `${TODAY}T07:45:00`,
    estimatedArrivalTime: `${TODAY}T08:30:00`,
    actualPickupTime: `${TODAY}T07:48:00`,
    actualArrivalTime: null,
    status: "InTransit",
    pickupAddress: "203 Pine Avenue, Springfield, IL 62703",
    dropoffAddress: "Memorial Medical Center, 701 N First St, Springfield, IL 62781",
    estimatedDistance: 8.5,
    estimatedDuration: 25,
    medicalNotes: "Requires portable oxygen concentrator. Mild dementia — may be confused.",
    specialInstructions: "Chaperone not available — driver to maintain calm conversation. Do not leave patient unattended.",
    accessibilityNeeds: ["wheelchair", "oxygen_equipment"],
    createdAt: `${TODAY}T06:30:00`,
    updatedAt: `${TODAY}T08:05:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T06:30:00`, status: "Scheduled", changedBy: "Dispatcher" },
      { timestamp: `${TODAY}T07:20:00`, status: "DriverEnRoute", changedBy: "Angela Thompson" },
      { timestamp: `${TODAY}T07:48:00`, status: "PassengerPickedUp", changedBy: "Angela Thompson" },
      { timestamp: `${TODAY}T08:05:00`, status: "InTransit", changedBy: "Angela Thompson" },
    ],
    notes: ["Patient needed extra time with oxygen setup"],
  },

  // Scheduled (upcoming)
  {
    id: "ride-4",
    confirmationNumber: "TR-20260409-004",
    passenger: mockPassengers[3],
    driver: mockDrivers[2],
    chaperone: mockChaperones[1],
    pickupTime: `${TODAY}T10:00:00`,
    estimatedArrivalTime: `${TODAY}T10:45:00`,
    actualPickupTime: null,
    actualArrivalTime: null,
    status: "Scheduled",
    pickupAddress: "556 Elm Court, Springfield, IL 62704",
    dropoffAddress: "Cardiovascular Associates, 3132 Old Jacksonville Rd, Springfield, IL 62711",
    estimatedDistance: 7.3,
    estimatedDuration: 20,
    medicalNotes: "Cardiac patient. Monthly cardiology follow-up. Has pacemaker.",
    specialInstructions: "Confirm appointment 30 min before pickup.",
    accessibilityNeeds: [],
    createdAt: `${TODAY}T06:00:00`,
    updatedAt: `${TODAY}T06:00:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T06:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
    ],
    notes: [],
  },

  // Scheduled
  {
    id: "ride-5",
    confirmationNumber: "TR-20260409-005",
    passenger: mockPassengers[4],
    driver: mockDrivers[3],
    chaperone: mockChaperones[3],
    pickupTime: `${TODAY}T11:30:00`,
    estimatedArrivalTime: `${TODAY}T12:15:00`,
    actualPickupTime: null,
    actualArrivalTime: null,
    status: "Scheduled",
    pickupAddress: "917 Birch Road, Springfield, IL 62705",
    dropoffAddress: "Springfield Dialysis Center, 800 N Grand Ave, Springfield, IL 62702",
    estimatedDistance: 6.8,
    estimatedDuration: 22,
    medicalNotes: "Dialysis patient — must not miss appointment. Cannot wait more than 15 min at pickup.",
    specialInstructions: "Call patient 20 min before arrival. Patient prefers window seat.",
    accessibilityNeeds: ["wheelchair"],
    createdAt: `${TODAY}T06:00:00`,
    updatedAt: `${TODAY}T06:00:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T06:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
    ],
    notes: [],
  },

  // Scheduled (afternoon)
  {
    id: "ride-6",
    confirmationNumber: "TR-20260409-006",
    passenger: mockPassengers[5],
    driver: mockDrivers[2],
    chaperone: mockChaperones[1],
    pickupTime: `${TODAY}T14:00:00`,
    estimatedArrivalTime: `${TODAY}T14:40:00`,
    actualPickupTime: null,
    actualArrivalTime: null,
    status: "Scheduled",
    pickupAddress: "34 Willow Way, Springfield, IL 62706",
    dropoffAddress: "Springfield Internal Medicine, 555 W Monroe St, Springfield, IL 62704",
    estimatedDistance: 5.1,
    estimatedDuration: 16,
    medicalNotes: "Diabetic. Insulin dependent. May need extra time at appointments.",
    specialInstructions: "Patient may have low blood sugar. Keep glucose tablets in vehicle.",
    accessibilityNeeds: ["cane"],
    createdAt: `${TODAY}T06:00:00`,
    updatedAt: `${TODAY}T06:00:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T06:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
    ],
    notes: [],
  },

  // Arrived
  {
    id: "ride-7",
    confirmationNumber: "TR-20260409-007",
    passenger: mockPassengers[6],
    driver: mockDrivers[0],
    chaperone: mockChaperones[0],
    pickupTime: `${TODAY}T06:30:00`,
    estimatedArrivalTime: `${TODAY}T07:10:00`,
    actualPickupTime: `${TODAY}T06:32:00`,
    actualArrivalTime: `${TODAY}T07:08:00`,
    status: "Arrived",
    pickupAddress: "72 Cedar Lane, Springfield, IL 62707",
    dropoffAddress: "Springfield Cancer Center, 315 W Carpenter St, Springfield, IL 62702",
    estimatedDistance: 9.1,
    estimatedDuration: 27,
    medicalNotes: "Oncology patient. Hearing impaired — speak clearly. Bi-weekly treatment.",
    specialInstructions: "Expect 2-3 hour appointment. Driver to wait on premises.",
    accessibilityNeeds: ["hearing_impaired"],
    createdAt: `${TODAY}T05:30:00`,
    updatedAt: `${TODAY}T07:08:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `${TODAY}T05:30:00`, status: "Scheduled", changedBy: "Dispatcher" },
      { timestamp: `${TODAY}T06:05:00`, status: "DriverEnRoute", changedBy: "Marcus Williams" },
      { timestamp: `${TODAY}T06:32:00`, status: "PassengerPickedUp", changedBy: "Marcus Williams" },
      { timestamp: `${TODAY}T06:45:00`, status: "InTransit", changedBy: "Marcus Williams" },
      { timestamp: `${TODAY}T07:08:00`, status: "Arrived", changedBy: "Marcus Williams" },
    ],
    notes: ["On time. Patient settled at cancer center."],
  },

  // Completed
  {
    id: "ride-8",
    confirmationNumber: "TR-20260409-008",
    passenger: mockPassengers[7],
    driver: mockDrivers[1],
    chaperone: mockChaperones[2],
    pickupTime: `${TODAY}T07:00:00`,
    estimatedArrivalTime: `${TODAY}T07:30:00`,
    actualPickupTime: `${TODAY}T07:02:00`,
    actualArrivalTime: `${TODAY}T07:31:00`,
    status: "Completed",
    pickupAddress: "291 Spruce Street, Springfield, IL 62708",
    dropoffAddress: "Midwest Neurology, 2200 S 6th St, Springfield, IL 62703",
    estimatedDistance: 4.5,
    estimatedDuration: 15,
    medicalNotes: "Parkinson's disease. Tremors may affect boarding. Allow extra time.",
    specialInstructions: "Assist with boarding. Chaperone to remain with patient throughout.",
    accessibilityNeeds: ["walker", "requires_assistance"],
    createdAt: `2026-04-08T18:00:00`,
    updatedAt: `${TODAY}T07:31:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `2026-04-08T18:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
      { timestamp: `${TODAY}T06:40:00`, status: "DriverEnRoute", changedBy: "Sarah Chen" },
      { timestamp: `${TODAY}T07:02:00`, status: "PassengerPickedUp", changedBy: "Sarah Chen", note: "Extra boarding time needed" },
      { timestamp: `${TODAY}T07:15:00`, status: "InTransit", changedBy: "Sarah Chen" },
      { timestamp: `${TODAY}T07:31:00`, status: "Arrived", changedBy: "Sarah Chen" },
      { timestamp: `${TODAY}T07:42:00`, status: "Completed", changedBy: "Sarah Chen", note: "Patient delivered safely" },
    ],
    notes: ["Patient in good spirits. Appointment confirmed."],
  },

  // Completed (older - history)
  {
    id: "ride-9",
    confirmationNumber: "TR-20260408-015",
    passenger: mockPassengers[8],
    driver: mockDrivers[3],
    chaperone: mockChaperones[1],
    pickupTime: `2026-04-08T09:00:00`,
    estimatedArrivalTime: `2026-04-08T09:45:00`,
    actualPickupTime: `2026-04-08T09:00:00`,
    actualArrivalTime: `2026-04-08T09:47:00`,
    status: "Completed",
    pickupAddress: "128 Aspen Drive, Springfield, IL 62709",
    dropoffAddress: "Springfield Lab Services, 1001 E Mason St, Springfield, IL 62702",
    estimatedDistance: 5.5,
    estimatedDuration: 18,
    medicalNotes: "Routine lab work. Generally cooperative.",
    specialInstructions: "None.",
    accessibilityNeeds: ["wheelchair"],
    createdAt: `2026-04-07T16:00:00`,
    updatedAt: `2026-04-08T10:05:00`,
    createdBy: "Dispatcher",
    cancelledAt: null,
    cancelledBy: null,
    cancelReason: null,
    timeline: [
      { timestamp: `2026-04-07T16:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
      { timestamp: `2026-04-08T08:40:00`, status: "DriverEnRoute", changedBy: "Priya Patel" },
      { timestamp: `2026-04-08T09:00:00`, status: "PassengerPickedUp", changedBy: "Priya Patel" },
      { timestamp: `2026-04-08T09:12:00`, status: "InTransit", changedBy: "Priya Patel" },
      { timestamp: `2026-04-08T09:47:00`, status: "Arrived", changedBy: "Priya Patel" },
      { timestamp: `2026-04-08T10:05:00`, status: "Completed", changedBy: "Priya Patel" },
    ],
    notes: [],
  },

  // Cancelled
  {
    id: "ride-10",
    confirmationNumber: "TR-20260408-012",
    passenger: mockPassengers[9],
    driver: mockDrivers[4],
    chaperone: null,
    pickupTime: `2026-04-08T14:00:00`,
    estimatedArrivalTime: `2026-04-08T14:50:00`,
    actualPickupTime: null,
    actualArrivalTime: null,
    status: "Cancelled",
    pickupAddress: "445 Hickory Blvd, Springfield, IL 62710",
    dropoffAddress: "Behavioral Health Partners, 720 N Bond St, Springfield, IL 62702",
    estimatedDistance: 7.0,
    estimatedDuration: 20,
    medicalNotes: "Mental health outpatient. Occasional anxiety.",
    specialInstructions: "Patient cancelled at last minute.",
    accessibilityNeeds: [],
    createdAt: `2026-04-08T08:00:00`,
    updatedAt: `2026-04-08T13:30:00`,
    createdBy: "Dispatcher",
    cancelledAt: `2026-04-08T13:30:00`,
    cancelledBy: "Patient",
    cancelReason: "Patient called to cancel — feeling unwell.",
    timeline: [
      { timestamp: `2026-04-08T08:00:00`, status: "Scheduled", changedBy: "Dispatcher" },
      { timestamp: `2026-04-08T13:30:00`, status: "Cancelled", changedBy: "Dispatcher", note: "Patient cancelled — feeling unwell" },
    ],
    notes: ["Reschedule requested for next week."],
  },
];

// ---------- Helper functions ----------
export function getRideById(id: string): Ride | undefined {
  return mockRides.find((r) => r.id === id);
}

export function getActiveRides(): Ride[] {
  return mockRides.filter((r) =>
    ["DriverEnRoute", "PassengerPickedUp", "InTransit", "Arrived"].includes(r.status)
  );
}

export function getTodaysRides(): Ride[] {
  return mockRides.filter((r) => r.pickupTime.startsWith(TODAY));
}

export function getUpcomingRides(): Ride[] {
  return mockRides.filter(
    (r) => r.status === "Scheduled" && r.pickupTime.startsWith(TODAY)
  );
}

export function getCompletedRides(): Ride[] {
  return mockRides.filter((r) =>
    ["Completed", "Cancelled", "NoShow"].includes(r.status)
  );
}

export function getDriverById(id: string): Driver | undefined {
  return mockDrivers.find((d) => d.id === id);
}

export function getChaperoneById(id: string): Chaperone | undefined {
  return mockChaperones.find((c) => c.id === id);
}

export function getAvailableDrivers(): Driver[] {
  return mockDrivers.filter((d) => d.status === "Available");
}

export function getAvailableChaperones(): Chaperone[] {
  return mockChaperones.filter((c) => c.status === "Available");
}
